### ISSUE TITLE
Panic when updating pulumi-random

### ISSUE THREAD

**Issue by t0yv0** [pulumi/upgrade-provider#85]
### What happened?

Based on

```
git rev-parse HEAD                                                                                                                                                            ~/code/pulumi-random
579790eae39462e26d4db2f87ca526d1b0d8d108
```

```
upgrade-provider pulumi/pulumi-random --experimental --kind bridge                                                                                                        ~/code/pulumi-random
---- Setting Up Environment ----
- ✓ GOWORK="off": done
- ✓ PULUMI_MISSING_DOCS_ERROR="true": done
- ✓ PULUMI_CONVERT_EXAMPLES_CACHE_DIR="": done
---- Discovering Repository ----
- Ensure 'github.com/pulumi/pulumi-random'
  - ✓ Expected Location: /Users/t0yv0/code/pulumi-random
  - ✓ Downloading: skipped
  - ✓ Validating: done
- pull default branch
  - ✓ /usr/bin/git ls-remote --heads origin: done
  - ✓ finding default branch: master
  - ✓ /usr/bin/git fetch: done
  - ✓ /usr/bin/git checkout master: done
  - ✓ /usr/bin/git pull origin: done
- ✓ Repo kind: shimmed
- ✓ Planning Bridge Update: v3.44.3 -> v3.47.2
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x13c70b6]

goroutine 1 [running]:
github.com/pulumi/upgrade-provider/upgrade.prBody({{0x1541418, 0xc00009e000}, {0xc00009e100, 0xf}, 0x0, 0x1, 0x1, 0x0, 0x0, 0x0, ...}, ...)
        github.com/pulumi/upgrade-provider/upgrade/steps-helpers.go:117 +0x4f6
github.com/pulumi/upgrade-provider/upgrade.InformGitHub({{0x1541418, 0xc00009e000}, {0xc00009e100, 0xf}, 0x0, 0x1, 0x1, 0x0, 0x0, 0x0, ...}, ...)
        github.com/pulumi/upgrade-provider/upgrade/steps.go:310 +0x378
github.com/pulumi/upgrade-provider/upgrade.UpgradeProvider({{0x1541418, 0xc00009e000}, {0xc00009e100, 0xf}, 0x0, 0x1, 0x1, 0x0, 0x0, 0x0, ...}, ...)
        github.com/pulumi/upgrade-provider/upgrade/upgrade-provider.go:295 +0x2bc9
main.cmd.func3(0xc000162000?, {0xc0000ad340?, 0x1?, 0x4?})
        github.com/pulumi/upgrade-provider/main.go:135 +0x66
github.com/spf13/cobra.(*Command).execute(0xc000162000, {0xc0000b2010, 0x4, 0x4})
        github.com/spf13/cobra@v1.6.1/command.go:920 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc000162000)
        github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
        github.com/pulumi/upgrade-provider/main.go:178 +0x1e
```

### Expected Behavior

No panic

### Steps to reproduce

See above

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by jaxxstorm** [comment]
I got the same error when upgrading pulumi-grafana

```
---- Setting Up Environment ----
- ✓ GOWORK="off": done
- ✓ PULUMI_MISSING_DOCS_ERROR="true": done
- ✓ PULUMI_CONVERT_EXAMPLES_CACHE_DIR="": done
---- Discovering Repository ----
- Ensure 'github.com/lbrlabs/pulumi-grafana'
  - ✓ Expected Location: /Users/lbriggs/src/github/lbrlabs/pulumi-grafana
  - ✓ Downloading: skipped
  - ✓ Validating: done
- pull default branch
  - ✓ /opt/homebrew/bin/git ls-remote --heads origin: done
  - ✓ finding default branch: main
  - ✓ /opt/homebrew/bin/git fetch: done
  - ✓ /opt/homebrew/bin/git checkout main: done
  - ✓ /opt/homebrew/bin/git pull origin: done
- ✓ Repo kind: shimmed
- / Planning Provider Updatepanic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x1051e2e90]

goroutine 1 [running]:
github.com/pulumi/upgrade-provider/upgrade.UpgradeProvider.func2()
	/Users/lbriggs/go/pkg/mod/github.com/pulumi/upgrade-provider@v0.0.0-20230517220859-1038026abbf2/upgrade/upgrade-provider.go:68 +0x180
github.com/pulumi/upgrade-provider/step.runIn[...](0x4?, 0x4?)
	/Users/lbriggs/go/pkg/mod/github.com/pulumi/upgrade-provider@v0.0.0-20230517220859-1038026abbf2/step/step.go:128 +0x15c
github.com/pulumi/upgrade-provider/step.step.run({{0x1051f1c53, 0x18}, 0x140001e2000, 0x0, 0x0}, {0x1051e6eb4, 0x2})
	/Users/lbriggs/go/pkg/mod/github.com/pulumi/upgrade-provider@v0.0.0-20230517220859-1038026abbf2/step/step.go:44 +0x184
github.com/pulumi/upgrade-provider/step.combined.run({{0x1051f04ee, 0x16}, {0x14000139600, 0x5, 0x8}, 0x0, {0x0, 0x0, 0x0}, 0x0}, ...)
	/Users/lbriggs/go/pkg/mod/github.com/pulumi/upgrade-provider@v0.0.0-20230517220859-1038026abbf2/step/step.go:261 +0x1b4
github.com/pulumi/upgrade-provider/step.Run(...)
	/Users/lbriggs/go/pkg/mod/github.com/pulumi/upgrade-provider@v0.0.0-20230517220859-1038026abbf2/step/step.go:279
github.com/pulumi/upgrade-provider/upgrade.UpgradeProvider({{0x1053554b0, 0x14000106000}, {0x1400012c078, 0x11}, 0x0, 0x1, 0x1, 0x1, 0x1, 0x0, ...}, ...)
	/Users/lbriggs/go/pkg/mod/github.com/pulumi/upgrade-provider@v0.0.0-20230517220859-1038026abbf2/upgrade/upgrade-provider.go:135 +0xb88
main.cmd.func3(0x140001d2000?, {0x14000101a70?, 0x1?, 0x1?})
	/Users/lbriggs/go/pkg/mod/github.com/pulumi/upgrade-provider@v0.0.0-20230517220859-1038026abbf2/main.go:135 +0x94
github.com/spf13/cobra.(*Command).execute(0x140001d2000, {0x14000120010, 0x1, 0x1})
	/Users/lbriggs/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x5b0
github.com/spf13/cobra.(*Command).ExecuteC(0x140001d2000)
	/Users/lbriggs/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/lbriggs/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
main.main()
	/Users/lbriggs/go/pkg/mod/github.com/pulumi/upgrade-provider@v0.0.0-20230517220859-1038026abbf2/main.go:178 +0x20
```
